### ISSUE TITLE
I met the same problem in importing the extension moudles. Could you public the built extension files (sparse_dot and bilinear_diag)?

### ISSUE THREAD

**Issue by pamela0530** [Thinklab-SJTU/ThinkMatch#22]
Could you public the built extension files (sparse_dot and bilinear_diag)?

**Comment by rogerwwww** [comment]
Hi there,

I am sorry for the late reply (I seem to have overlooked this issue). 

Unfortunately, I fail to find the built extension files because they are compiled by Pytorch's JIT, and it seems that JIT does not provide the compiled binaries (I am not sure, and please let me know if they can be found somewhere). 

In other ways, could you please post your error message so that we can look into your issue?

**Comment by rogerwwww** [comment]
Hi, I am closing this issue since there are no follow-ups. If anyone has any questions, just feel free to reopen it.
