### ISSUE TITLE
Confused on the origin edge attribution.

### ISSUE THREAD

**Issue by C-puqing** [Thinklab-SJTU/ThinkMatch#37]
Hi, I am new to the deep graph matching and am very interested in your work.
I am confused by [line 71-72](https://github.com/Thinklab-SJTU/ThinkMatch/blob/9d33c1516a9a13e7d4a111133ec4e0e2af798d50/src/dataset/data_loader.py#L71-L72). 
Why do you clip the edge_attr into the interval [0, 1] when you create a pyg graph?
```
        edge_attr = np.clip(edge_attr, 0, 1)
        assert (edge_attr > -1e-5).all(), P
```

In fact, I find that the coordinates of image keypoints have negative values. I'm new to image datasets, so I don't know if negative values should be there. So, I guessed you do the clip to get rid of negative values of keypoints.

**Comment by rogerwwww** [comment]
Hi there,

Yes, it is because the coordinates of image keypoints may have negative values. For the Pascal VOC dataset, the images are cropped based on the bounding box. However, the dataset does not guarantee the keypoint positions must lie within the bounding box, thus you are seeing keypoints with negative values.

If the edge attr has negative values, pyg will throw an error. Thus we are tackling this issue with the clipping method.

**Comment by C-puqing** [comment]
Thanks for your explaination.  I am clear about it now.
