### ISSUE TITLE
NGM learns nothing for QAP. Non-trained NGM performs similarly to the results posted in the paper.

### ISSUE THREAD

**Issue by Bincci** [Thinklab-SJTU/ThinkMatch#42]
> Hi, I am sorry for the late reply and I might have overlooked the recent post.
> 
> I agree that aspects like post-processing do contribute to the performance. Just a personal note here: according to my experience, for the `bur` instances, the trained NGM model will perform better than the non-trained NGM model, though the loss curves may be as noisy as you have mentioned.

I reproduced your experiments. I am pretty sure that the non-trained NGM model performs similarly to the trained NGM model, and the results of non-trained NGM model are similar to the results you posted in the paper. TBH, the proposed model is useless, at least for QAPLIB problems.

If you have any results showing that the trained NGM performs better than non-trained NGM on QAPLIB instances, please post here.

_Originally posted by @Bincci in https://github.com/Thinklab-SJTU/ThinkMatch/issues/36#issuecomment-1049811335_

**Comment by rogerwwww** [comment]
Hi there! Your following-up comments and experiments are very thought-provoking, which we deeply cherish. Regarding your concern that has not been aware when we were working on this paper, I did a quick experiment on 119 QAPLIB instances. (Not all instances because our RTX8000 is currently busy and I wish a quick reply for you.)

So here is my conclusion: the non-trained NGM model performs similarly to the trained NGM model on certain instances, but still worse in general. On the 119 QAPLIB instances studied:
* Trained NGM is better: 76 / 119
* Non-trained NGM is better: 38 / 119
* The same: 5 / 119

Please check the following log file for details:
[eval_2022-02-24-21-00-48.xls](https://github.com/Thinklab-SJTU/ThinkMatch/files/8132708/eval_2022-02-24-21-00-48.xls)

Though for the majority of instances, trained NGM is better, I did not expect there is still a portion of instances where non-trained NGM is better (which suggests that the randomness in Gumbel sampling may contribute more to the performance), and I find it quite interesting. I will look into these instances and re-thinking about why or why not the learning part will work on these instances.

Finally, thanks again for your in-depth discussions which really inspire me. If you have any further ideas, feel free to let me know.

**Comment by binqi-sun** [comment]
Thanks for your reply and quick experiment. I was quite interested in your paper, and was attracted by the good results. So I tried to understand which part contributes to the good performance the most. I also did some little experiments to see how the performance varies with the number of Gumbel samplings performed in the post-processing, and found that the performance will get much worse when fewer samplings are used.

But anyway, the paper inspired me a lot, and those problems are very interesting. Looking forward to reading more works on this in the future.

**Comment by Bincci** [comment]
Thanks for your reply and quick experiment. I was quite interested in your paper, and was attracted by the good results. So I tried to understand which part contributes to the good performance the most. I also did some little experiments to see how the performance varies with the number of Gumbel samplings performed in the post-processing, and found that the performance will get much worse when fewer samplings are used.

But anyway, the paper inspired me a lot, and the topic is very interesting. Looking forward to reading more works on this in the future.
